name: polybar-git
adopt-info: polybar-git
summary: A fast and easy-to-use status bar
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

base: core18
grade: devel
confinement: devmode

# plugs:
#   polybar-config:
#     interface: personal-files
#     read:
#       - $HOME/.config/polybar


apps:
  polybar-git:
    command: usr/local/bin/polybar
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$LD_LIBRARY_PATH"
      XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR
    plugs: 
      - network
      - network-bind
      - unity7
      - opengl
      - home
      - pulseaudio
      - desktop
      - desktop-legacy
      - removable-media
      - x11
      - wayland
      - fuse-support
      - mount-observe
      - raw-usb
      - bluetooth-control
      - bluez
      - device-buttons
      - hardware-observe
      - location-observe
      - udisks2
      - io-ports-control
      - media-hub
      - mpris
      - modem-manager
      - network-control
      - network-manager-observe
      - network-status
      - physical-memory-observe
      - process-control
      - serial-port
      - shutdown
      - system-trace
      - upower-observe


parts:
  polybar-git:
    plugin: autotools
    source: https://github.com/polybar/polybar.git
    source-type: git
    build-packages: 
      - build-essential
      - git
      - cmake
      - cmake-data
      - pkg-config
      - python3-sphinx
      - libcairo2-dev
      - libxcb1-dev
      - libxcb-util0-dev
      - libxcb-randr0-dev
      - libxcb-composite0-dev
      - python-xcbgen
      - xcb-proto
      - libxcb-image0-dev
      - libxcb-ewmh-dev
      - libxcb-icccm4-dev
      - libxcb-xkb-dev
      - libxcb-xrm-dev
      - libxcb-cursor-dev
      - libasound2-dev
      - libpulse-dev
      - i3-wm
      - libjsoncpp-dev
      - libmpdclient-dev
      - libcurl4-openssl-dev
      - libnl-genl-3-dev
    stage-packages:
      - libasn1-8-heimdal
      - libasound2
      - libasyncns0
      - libcairo2
      - libcurl4
      - libflac8
      - libfontconfig1
      - libfreetype6
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libmpdclient2
      - libnghttp2-14
      - libogg0
      - libpixman-1-0
      - libpng16-16
      - libpsl5
      - libpulse0
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libsndfile1
      - libvorbis0a
      - libvorbisenc2
      - libwind0-heimdal
      - libx11-6
      - libxau6
      - libxcb-composite0
      - libxcb-cursor0
      - libxcb-ewmh2
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-render0
      - libxcb-shm0
      - libxcb-util1
      - libxcb-xkb1
      - libxcb-xrm0
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxrender1
      - i3
    override-pull: |
       snapcraftctl pull
       last_committed_tag="$(git tag -l | grep -v v | sort -rV | head -n1)"
       snapcraftctl set-version "${last_committed_tag}"
    override-build: |
      cmake \
        -DCMAKE_CXX_COMPILER="c++" \
        -DENABLE_ALSA:BOOL="ON" \
        -DENABLE_PULSEAUDIO:BOOL="ON" \
        -DENABLE_I3:BOOL="ON" \
        -DENABLE_MPD:BOOL="ON" \
        -DENABLE_NETWORK:BOOL="ON" \
        -DENABLE_CURL:BOOL="ON" \
        -DBUILD_IPC_MSG:BOOL="ON" \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_PART_INSTALL/usr/local
      make
      make install
